--[[
    CONSTANTS
    CS50G Project 3
    Match 3
    Author: Maxime Blanc
    https://github.com/salty-max
--]]

VIRTUAL_WIDTH = 512
VIRTUAL_HEIGHT = 288

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

BACKGROUND_SCROLL_SPEED = 80
BACKGROUND_LOOPING_POINT = VIRTUAL_WIDTH + 47

BOARD_OFFSET_X = VIRTUAL_WIDTH - 288
BOARD_OFFSET_Y = 16